version: '3'

services:
  db:
    image: sqlite:latest
    environment:
      - SQLITE_DATABASE=teamtracker
  web:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/db.sqlite3
      - SECRET_KEY=secret_key
      - DEBUG=True
      - ALLOWED_HOSTS=*
    depends_on:
      - db
